from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector
import sys
from main_frame import main  as main_run ,retranslateUi as main_run2

class report_page(object):
    def setupUi(self, home):
        home.setObjectName("home")
        home.resize(1920, 1000)
        home.setStyleSheet("QFrame#left_nav,QFrame#top_nav{background-color: #1C2B36;}QPushButton{color:rgb(255, 255, 255);}QFrame#b1:hover,QFrame#b2:hover,QFrame#b3:hover,QFrame#b4:hover,QFrame#b5:hover{background-color: #219E91;color:rgb(255, 255, 255);}QFrame#main{background-color: rgb(240, 243, 244);}QLineEdit#Search_bar{background-color: #1C2B36;color:#17B7A6;border:0%;}QFrame#name_find,QFrame#name_find_2,QFrame#name_find_3,QFrame#name_find_4,QFrame#name_find_5,QFrame#name_find_6,QFrame#name_find_7,QFrame#name_find_8{background-color: rgb(255, 255, 255);border : 1px solid rgb(163, 163, 163);border-radius : 5px;}QLineEdit#std_name_find{border : 0%;}")
        self.centralwidget = QtWidgets.QWidget(home)
        self.centralwidget.setObjectName("centralwidget")
        self.left_nav = QtWidgets.QFrame(self.centralwidget)
        self.left_nav.setGeometry(QtCore.QRect(0, 0, 340, 1000))
        self.left_nav.setStyleSheet("")
        self.left_nav.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_nav.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_nav.setObjectName("left_nav")
        self.b1 = QtWidgets.QFrame(self.left_nav)
        self.b1.setGeometry(QtCore.QRect(0, 110, 340, 50))
        self.b1.setStyleSheet("")
        self.b1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b1.setObjectName("b1")
        self.btn1 = QtWidgets.QPushButton(self.b1)
        self.btn1.setGeometry(QtCore.QRect(0, 0, 340, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn1.setFont(font)
        self.btn1.setFocusPolicy(QtCore.Qt.WheelFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("gui/icons/white/home.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn1.setIcon(icon)
        self.btn1.setDefault(True)
        self.btn1.setFlat(True)
        self.btn1.setObjectName("btn1")
        self.b2 = QtWidgets.QFrame(self.left_nav)
        self.b2.setGeometry(QtCore.QRect(0, 160, 340, 50))
        self.b2.setStyleSheet("")
        self.b2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b2.setObjectName("b2")
        self.btn2 = QtWidgets.QPushButton(self.b2)
        self.btn2.setGeometry(QtCore.QRect(0, 0, 340, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn2.setFont(font)
        self.btn2.setFocusPolicy(QtCore.Qt.WheelFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("gui/icons/white/attendance.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn2.setIcon(icon1)
        self.btn2.setDefault(True)
        self.btn2.setFlat(True)
        self.btn2.setObjectName("btn2")
        self.b3 = QtWidgets.QFrame(self.left_nav)
        self.b3.setGeometry(QtCore.QRect(0, 210, 340, 50))
        self.b3.setStyleSheet("")
        self.b3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b3.setObjectName("b3")
        self.btn3 = QtWidgets.QPushButton(self.b3)
        self.btn3.setGeometry(QtCore.QRect(0, 0, 340, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn3.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("gui/icons/white/student.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn3.setIcon(icon2)
        self.btn3.setDefault(True)
        self.btn3.setFlat(True)
        self.btn3.setObjectName("btn3")
        self.b4 = QtWidgets.QFrame(self.left_nav)
        self.b4.setGeometry(QtCore.QRect(0, 260, 340, 50))
        self.b4.setStyleSheet("")
        self.b4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.b4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.b4.setObjectName("b4")
        self.btn4 = QtWidgets.QPushButton(self.b4)
        self.btn4.setGeometry(QtCore.QRect(0, 0, 340, 50))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn4.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("gui/icons/white/setting.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn4.setIcon(icon3)
        self.btn4.setDefault(True)
        self.btn4.setFlat(True)
        self.btn4.setObjectName("btn4")
        self.college_name = QtWidgets.QLabel(self.left_nav)
        self.college_name.setGeometry(QtCore.QRect(100, 0, 240, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.college_name.setFont(font)
        self.college_name.setStyleSheet("color: #ffffff;")
        self.college_name.setObjectName("college_name")
        self.label = QtWidgets.QLabel(self.left_nav)
        self.label.setGeometry(QtCore.QRect(20, 20, 60, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("gui/img/college_Logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.top_nav = QtWidgets.QFrame(self.centralwidget)
        self.top_nav.setGeometry(QtCore.QRect(340, 0, 1580, 75))
        self.top_nav.setStyleSheet("")
        self.top_nav.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_nav.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_nav.setObjectName("top_nav")
        self.Search_bar = QtWidgets.QLineEdit(self.top_nav)
        self.Search_bar.setGeometry(QtCore.QRect(110, 25, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Search_bar.setFont(font)
        self.Search_bar.setObjectName("Search_bar")
        self.search = QtWidgets.QPushButton(self.top_nav)
        self.search.setGeometry(QtCore.QRect(50, 30, 25, 25))
        self.search.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("gui/icons/white/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search.setIcon(icon4)
        self.search.setIconSize(QtCore.QSize(25, 25))
        self.search.setDefault(True)
        self.search.setFlat(True)
        self.search.setObjectName("search")
        self.profile = QtWidgets.QFrame(self.top_nav)
        self.profile.setGeometry(QtCore.QRect(1200, 10, 330, 60))
        self.profile.setStyleSheet("")
        self.profile.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.profile.setFrameShadow(QtWidgets.QFrame.Raised)
        self.profile.setObjectName("profile")
        self.label_2 = QtWidgets.QLabel(self.profile)
        self.label_2.setGeometry(QtCore.QRect(240, 0, 60, 60))
        self.label_2.setStyleSheet("background-color: rgb(85, 25, 255);border-radius: 30%;")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("gui/icons/profile.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.name = QtWidgets.QLabel(self.profile)
        self.name.setGeometry(QtCore.QRect(110, 13, 121, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.name.setFont(font)
        self.name.setStyleSheet("color:#ffffff;")
        self.name.setObjectName("name")
        self.main.setGeometry(QtCore.QRect(340, 80, 1580, 925))
        self.main = QtWidgets.QFrame(home)
        self.main_run()


        self.retranslateUi(home)
        QtCore.QMetaObject.connectSlotsByName(home)
    def getdata(self):
        mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        password="2022",
        database= "face"    
        )

        cur = mydb.cursor()

        cur.execute("SELECT * FROM student;")
        result = cur.fetchall()
        self.tableWidget.setRowCount(0)
        for row_number , row_data in enumerate(result):
             self.tableWidget.insertRow(row_number)
             for col_number , data in enumerate(row_data):
                  self.tableWidget.setItem(row_number,col_number,QtWidgets.QTableWidgetItem(str(data)))
    def searchdate(self):
        mydb = mysql.connector.connect(
        host="localhost",
        user="root",
        password="2022",
        database= "face"    
        )

        cur = mydb.cursor()

        cur.execute("select * from student where s_name ='kamlesh' ; ")
        result = cur.fetchall()
        self.tableWidget.setRowCount(0)
        for row_number , row_data in enumerate(result):
             self.tableWidget.insertRow(row_number)
             for col_number , data in enumerate(row_data):
                  self.tableWidget.setItem(row_number,col_number,QtWidgets.QTableWidgetItem(str(data)))
    def retranslateUi(self, home):
        _translate = QtCore.QCoreApplication.translate
        home.setWindowTitle(_translate("home", "MainWindow"))
        self.btn1.setText(_translate("home", "     Dashboard                    "))
        self.btn2.setText(_translate("home", "     Report                          "))
        self.btn3.setText(_translate("home", "     Student List                  "))
        self.btn4.setText(_translate("home", "     Settings                       "))
        self.college_name.setText(_translate("home", "SSR COLLEGE \nATTENDANCE SYSTEM"))
        self.Search_bar.setPlaceholderText(_translate("home", "Search Student by ID..."))
        self.name.setText(_translate("home", "name "))



if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = report_page()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())
