import sys

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_index(object):
    def setupUi(self, index):
        index.setObjectName("index")
        index.setEnabled(True)
        index.resize(1919, 1000)

        index.setStyleSheet("")
        
        self.centralwidget = QtWidgets.QWidget(index)
        self.centralwidget.setObjectName("centralwidget")
        self.menu = QtWidgets.QFrame(self.centralwidget)
        self.menu.setGeometry(QtCore.QRect(0, 99, 281, 901))
        self.menu.setStyleSheet("QFrame{\n"
"border-radius: 10%;\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{\n"
"    border-radius: 10%;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #0075FF;\n"
"    color:rgb(255, 255, 255);\n"
"}")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.logout_btn = QtWidgets.QPushButton(self.menu)
        self.logout_btn.setGeometry(QtCore.QRect(12, 810, 257, 63))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.logout_btn.setFont(font)
        self.logout_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.logout_btn.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.logout_btn.setAutoFillBackground(False)
        self.logout_btn.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"border-radius: 10%;")
        self.logout_btn.setIconSize(QtCore.QSize(20, 20))
        self.logout_btn.setShortcut("")
        self.logout_btn.setDefault(True)
        self.logout_btn.setFlat(True)
        self.logout_btn.setObjectName("logout_btn")
        self.btn1 = QtWidgets.QFrame(self.menu)
        self.btn1.setGeometry(QtCore.QRect(0, 10, 280, 80))
        self.btn1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn1.setObjectName("btn1")
        self.dashboard_button = QtWidgets.QPushButton(self.btn1)
        self.dashboard_button.setGeometry(QtCore.QRect(10, 10, 257, 63))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.dashboard_button.setFont(font)
        self.dashboard_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboard_button.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dashboard_button.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dashboard_button.setAutoFillBackground(False)
        self.dashboard_button.setStyleSheet("")
        self.dashboard_button.setIconSize(QtCore.QSize(20, 20))
        self.dashboard_button.setShortcut("")
        self.dashboard_button.setDefault(True)
        self.dashboard_button.setFlat(True)
        self.dashboard_button.setObjectName("dashboard_button")
        self.btn1_2 = QtWidgets.QFrame(self.menu)
        self.btn1_2.setGeometry(QtCore.QRect(0, 90, 280, 80))
        self.btn1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn1_2.setObjectName("btn1_2")
        self.dashboard_button_2 = QtWidgets.QPushButton(self.btn1_2)
        self.dashboard_button_2.setGeometry(QtCore.QRect(10, 10, 257, 63))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.dashboard_button_2.setFont(font)
        self.dashboard_button_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboard_button_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dashboard_button_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dashboard_button_2.setAutoFillBackground(False)
        self.dashboard_button_2.setStyleSheet("")
        self.dashboard_button_2.setIconSize(QtCore.QSize(20, 20))
        self.dashboard_button_2.setShortcut("")
        self.dashboard_button_2.setDefault(True)
        self.dashboard_button_2.setFlat(True)
        self.dashboard_button_2.setObjectName("dashboard_button_2")
        self.btn1_3 = QtWidgets.QFrame(self.menu)
        self.btn1_3.setGeometry(QtCore.QRect(0, 170, 280, 80))
        self.btn1_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn1_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn1_3.setObjectName("btn1_3")
        self.dashboard_button_3 = QtWidgets.QPushButton(self.btn1_3)
        self.dashboard_button_3.setGeometry(QtCore.QRect(10, 10, 257, 63))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.dashboard_button_3.setFont(font)
        self.dashboard_button_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboard_button_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dashboard_button_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dashboard_button_3.setAutoFillBackground(False)
        self.dashboard_button_3.setStyleSheet("")
        self.dashboard_button_3.setIconSize(QtCore.QSize(20, 20))
        self.dashboard_button_3.setShortcut("")
        self.dashboard_button_3.setDefault(True)
        self.dashboard_button_3.setFlat(True)
        self.dashboard_button_3.setObjectName("dashboard_button_3")
        self.btn1_4 = QtWidgets.QFrame(self.menu)
        self.btn1_4.setGeometry(QtCore.QRect(0, 260, 280, 80))
        self.btn1_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.btn1_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.btn1_4.setObjectName("btn1_4")
        self.dashboard_button_4 = QtWidgets.QPushButton(self.btn1_4)
        self.dashboard_button_4.setGeometry(QtCore.QRect(10, 10, 257, 63))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.dashboard_button_4.setFont(font)
        self.dashboard_button_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dashboard_button_4.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.dashboard_button_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dashboard_button_4.setAutoFillBackground(False)
        self.dashboard_button_4.setStyleSheet("")
        self.dashboard_button_4.setIconSize(QtCore.QSize(20, 20))
        self.dashboard_button_4.setShortcut("")
        self.dashboard_button_4.setDefault(True)
        self.dashboard_button_4.setFlat(True)
        self.dashboard_button_4.setObjectName("dashboard_button_4")
        self.logo = QtWidgets.QFrame(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(0, 0, 281, 101))
        self.logo.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setGeometry(QtCore.QRect(280, 0, 1640, 100))
        self.top_bar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.profile_img = QtWidgets.QLabel(self.top_bar)
        self.profile_img.setGeometry(QtCore.QRect(1524, 20, 60, 60))
        self.profile_img.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 30%;")
        self.profile_img.setObjectName("profile_img")
        self.search = QtWidgets.QFrame(self.top_bar)
        self.search.setGeometry(QtCore.QRect(1010, 25, 401, 50))
        self.search.setStyleSheet("background-color: #F3F3F3;\n"
"border-radius: 25%;")
        self.search.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.search.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search.setObjectName("search")
        self.search_bar = QtWidgets.QLineEdit(self.search)
        self.search_bar.setGeometry(QtCore.QRect(50, 7, 341, 35))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.search_bar.setFont(font)
        self.search_bar.setObjectName("search_bar")
        self.icon_search = QtWidgets.QLabel(self.search)
        self.icon_search.setGeometry(QtCore.QRect(14, 13, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.icon_search.setFont(font)
        self.icon_search.setText("")
        self.icon_search.setTextFormat(QtCore.Qt.AutoText)
        self.icon_search.setPixmap(QtGui.QPixmap("gui/icons/search.png"))
        self.icon_search.setScaledContents(True)
        self.icon_search.setOpenExternalLinks(False)
        self.icon_search.setObjectName("icon_search")
        self.title = QtWidgets.QLabel(self.top_bar)
        self.title.setGeometry(QtCore.QRect(80, 30, 431, 41))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(26)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.title.setFont(font)
        self.title.setObjectName("title")
        self.main = QtWidgets.QFrame(self.centralwidget)
        self.main.setGeometry(QtCore.QRect(280, 100, 1641, 900))
        self.main.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.retranslateUi(Form)
     
    def retranslateUi(self, index):
        _translate = QtCore.QCoreApplication.translate
        index.setWindowTitle(_translate("index", "MainWindow"))
        self.logout_btn.setText(_translate("index", "Logout"))
        self.dashboard_button.setText(_translate("index", "Dashboard"))
        self.dashboard_button_2.setText(_translate("index", "Dashboard"))
        self.dashboard_button_3.setText(_translate("index", "Dashboard"))
        self.dashboard_button_4.setText(_translate("index", "Dashboard"))
        self.profile_img.setText(_translate("index", "TextLabel"))
        self.search_bar.setPlaceholderText(_translate("index", "Search Student by ID"))
        self.title.setText(_translate("index", "Dashboard"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_index()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())
